### PR TITLE
Updated dependencies and release for 2.13

### PR DESCRIPTION
**Pull request by tomasherman**

### CODE REVIEW

**Comment by mijicd** [comment]
Can you also rename `ScalazBuild` to `BuildHelper`?

**Review by mijicd — COMMENTED** [review]
It looks good! Make sure to add the actual publishing step, and we can merge & release it.

**Comment by tomasherman** [comment]
Right, for some reason this doesn't run `test213_jvm_jdk8` test :( Pls can you verify that circleci is correct? I'm not very experienced with it ;)

**Comment by tomasherman** [comment]
nvm i fixed it ;)

**Comment by tomasherman** [comment]
so it turns out silencer is not released for 2.13.1 so we are stuck on 2.13.0 for now

**Review by mijicd — APPROVED** [review]

**Pull request merged**
